### ISSUE TITLE
backtick should probably be called qx()

### ISSUE THREAD

**Issue by jarich** [scrottie/autobox-Core#16]
Or there might be an alias.

**Comment by scrottie** [comment]
I got wedged up on this, wanting to pull operators and the like out, but then not having the energy/time to do the full major version/deprecation cycle to make that happen, and finally accepting that I'm not likely to after all.  So created an alias here and changed the docs to doc the qx for consistency, leaving backtick() for back compat.  Thanks jarich for raising this point and apologies for dragging my feet forever.
