### ISSUE TITLE
[PATCH] fix a spelling mistake

### ISSUE THREAD

**Issue by gregoa** [scrottie/autobox-Core#28]
In Debian we are currently applying the following patch to
autobox-Core.
We thought you might be interested in it too.

    Description: fix a spelling mistake
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2015-11-30
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libautobox-core-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by xenu** [comment]
Thank you, patch applied!

**Comment by scrottie** [comment]
=)

**Comment by gregoa** [comment]
On Mon, 30 Nov 2015 11:50:56 -0800, xenu wrote:

> Thank you, patch applied!

Wow, that was fast :)
Thanks!
