### ISSUE TITLE
[PATCH] fix a spelling mistake

### ISSUE THREAD

**Issue by gregoa** [scrottie/autobox-Core#31]
In Debian we are currently applying the following patch to
autobox-Core.
We thought you might be interested in it too.

    Description: fix a spelling mistake
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-01-07
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libautobox-core-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by xenu** [comment]
Thank you!

**Comment by gregoa** [comment]
On Thu, 07 Jan 2016 11:22:28 -0800, xenu wrote:

> Thank you!

Thanks to you :)


Cheers,
gregor

-- 
 .''`.  Homepage https://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Tom Waits: Baby Gonna Leave Me
